telegram:
  bot:
    username: ${BOT_NAME}
    token: ${BOT_TOKEN}
    notify:
      delay:
        value: 10
        unit: MINUTES
      cron: "0 */2 * * * ?"
#        value: 30
#        unit: SECONDS

binance:
  api:
    getPrice: https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
#      ddl-auto: create
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: crypto_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS crypto_schema
      connection-timeout: 10000